### ISSUE TITLE
ESP32 support

### ISSUE THREAD

**Issue by DmitryBorisenko33** [Toshik/TickerScheduler#20]
This is a very good library. For every day using. Very good and very useful.
This is link to my project where I use your library: https://github.com/DmitryBorisenko33/esp8266_iot-manager_modules_firmware
We try to use this library with ESP32 and got an error.
Can you please add ESP32 support for this library.

**Comment by DmitryBorisenko33** [comment]
![this is error:](https://user-images.githubusercontent.com/49808844/66708292-dc452480-ed56-11e9-8d0d-cd9ad04ca9df.png)

**Comment by DmitryBorisenko33** [comment]
```
'Ticker' does not name a type

     Ticker t;
```

**Comment by Sivolday** [comment]
And had a similar problem. Replace "ARDUINO_ARCH_ESP8266" with "ARDUINO_ARCH_ESP32" in "TickerScheduler.h" line 46, it fix error.
![image](https://user-images.githubusercontent.com/30410315/68448682-db4cc900-0216-11ea-8ba9-4ac6c75c5732.png)
