### ISSUE TITLE
Where would the ticker.h file come from?

### ISSUE THREAD

**Issue by mrohner** [Toshik/TickerScheduler#3]
C:\Users\Markus Rohner\Documents\Arduino\libraries\TickerScheduler/TickerScheduler.h:1:20: fatal error: Ticker.h: No such file or directory

 #include <Ticker.h>

                    ^

**Comment by Toshik** [comment]
It is standard library contained in ESP8266 board package - https://github.com/esp8266/Arduino

**Comment by RudyFiero** [comment]
More specifically - https://github.com/esp8266/Arduino/tree/master/libraries/Ticker

It should compile as it is an included library.
